title: Ilia Udalov
email: UdalovIlia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my homepage.
  I am on software development ğŸ› ï¸, art ğŸ¨ and longboardingğŸ›¹
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: UdalovIlia
github_username:  iudalov
facebook_username: UdalovIlia
linkedin_username: UdalovIlia
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
